name = "vtwo-ops"
type = "javascript"
main = "index.html"
compatibility_date = "2024-01-01"

[env.production]
routes = [{ pattern = "ats-hris.vtwo.co", zone_name = "vtwo.co" }]

[build]
command = "node build.js"
